# Generated by Django 4.2 on 2024-01-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=0, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
