# Generated by Django 4.2 on 2024-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default=0, upload_to='product_icon'),
            preserve_default=False,
        ),
    ]
